-- Yamaha ycz
INSERT INTO `tienda_motos`.`moto` ( `marca`, `linea`, `modelo`, `imagen`, `color`, `precio`, `descripcion`, `cilindraje`, `cantidad`, `categoria`) VALUES ( 'Yamaha', 'YBC', '2021', 'https://github.com/swsbmm/proyectoModelos1/blob/master/fotografias/Yamaha/YCZ/negro-rojo.jpg', 'Negro', '4350000', 'Peso (con aceite y tanque de gasolina lleno):96 kg\nPotencia máxima: 7.3 Hp a 7000 rpm\nTorque máximo: 8,6 Nm a 4500 rpm\nTipo de motor:4 Tiempos SOHC, refrigerado por aire\n', '110', '100', 'Urbano');
INSERT INTO `tienda_motos`.`moto` ( `marca`, `linea`, `modelo`, `imagen`, `color`, `precio`, `descripcion`, `cilindraje`, `cantidad`, `categoria`) VALUES ( 'Yamaha', 'YBC', '2021', 'https://github.com/swsbmm/proyectoModelos1/blob/master/fotografias/Yamaha/YCZ/yamaha-ycz-110-azul-1.jpg', 'Azul', '4350000', 'Peso (con aceite y tanque de gasolina lleno):96 kg\nPotencia máxima: 7.3 Hp a 7000 rpm\nTorque máximo: 8,6 Nm a 4500 rpm\nTipo de motor:4 Tiempos SOHC, refrigerado por aire\n', '110', '100', 'Urbano');
INSERT INTO `tienda_motos`.`moto` ( `marca`, `linea`, `modelo`, `imagen`, `color`, `precio`, `descripcion`, `cilindraje`, `cantidad`, `categoria`) VALUES ( 'Yamaha', 'YBC', '2021', 'https://github.com/swsbmm/proyectoModelos1/blob/master/fotografias/Yamaha/YCZ/yamaha-ycz-110-roja-1.jpg', 'Rojo', '4350000', 'Peso (con aceite y tanque de gasolina lleno):96 kg\nPotencia máxima: 7.3 Hp a 7000 rpm\nTorque máximo: 8,6 Nm a 4500 rpm\nTipo de motor:4 Tiempos SOHC, refrigerado por aire\n', '110', '100', 'Urbano');


-- Yamaha fz
INSERT INTO `tienda_motos`.`moto` (`marca`, `linea`, `modelo`, `imagen`, `color`, `precio`, `descripcion`, `cilindraje`, `cantidad`, `categoria`) VALUES ( 'Yamaha', 'FZ', '2021', 'https://github.com/swsbmm/proyectoModelos1/blob/master/fotografias/Yamaha/FZ/fz-azul.jpg', 'Azul', '7200000', 'Peso (con aceite y tanque de gasolina lleno): 133 kg\nPotencia Máxima: 13 Hp a 8000 rpm\nTorque máximo: 12.8 Nm a 6000 rpm\nTipo de motor: 4 Tiempos SOHC, refrigerado por aire\n', '149', '100', 'Urbano');
INSERT INTO `tienda_motos`.`moto` ( `marca`, `linea`, `modelo`, `imagen`, `color`, `precio`, `descripcion`, `cilindraje`, `cantidad`, `categoria`) VALUES ( 'Yamaha', 'FZ', '2021', 'https://github.com/swsbmm/proyectoModelos1/blob/master/fotografias/Yamaha/FZ/fz-black_mate.jpg', 'Negro Mate', '7200000', 'Peso (con aceite y tanque de gasolina lleno): 133 kg\nPotencia Máxima: 13 Hp a 8000 rpm\nTorque máximo: 12.8 Nm a 6000 rpm\nTipo de motor: 4 Tiempos SOHC, refrigerado por aire\n', '149', '100', 'Urbano');
INSERT INTO `tienda_motos`.`moto` (`marca`, `linea`, `modelo`, `imagen`, `color`, `precio`, `descripcion`, `cilindraje`, `cantidad`, `categoria`) VALUES ( 'Yamaha', 'FZ', '2021', 'https://github.com/swsbmm/proyectoModelos1/blob/master/fotografias/Yamaha/FZ/fz-blanca.jpg', 'Blanco', '7200000', 'Peso (con aceite y tanque de gasolina lleno): 133 kg\nPotencia Máxima: 13 Hp a 8000 rpm\nTorque máximo: 12.8 Nm a 6000 rpm\nTipo de motor: 4 Tiempos SOHC, refrigerado por aire\n', '149', '100', 'Urbano');
INSERT INTO `tienda_motos`.`moto` (`marca`, `linea`, `modelo`, `imagen`, `color`, `precio`, `descripcion`, `cilindraje`, `cantidad`, `categoria`) VALUES ( 'Yamaha', 'FZ', '2021', 'https://github.com/swsbmm/proyectoModelos1/blob/master/fotografias/Yamaha/FZ/fz-gris.jpg', 'Gris', '7200000', 'Peso (con aceite y tanque de gasolina lleno): 133 kg\nPotencia Máxima: 13 Hp a 8000 rpm\nTorque máximo: 12.8 Nm a 6000 rpm\nTipo de motor: 4 Tiempos SOHC, refrigerado por aire\n', '149', '100', 'Urbano');
INSERT INTO `tienda_motos`.`moto` (`marca`, `linea`, `modelo`, `imagen`, `color`, `precio`, `descripcion`, `cilindraje`, `cantidad`, `categoria`) VALUES ( 'Yamaha', 'FZ', '2021', 'https://github.com/swsbmm/proyectoModelos1/blob/master/fotografias/Yamaha/FZ/fz-roja.jpg', 'Roja', '7200000', 'Peso (con aceite y tanque de gasolina lleno): 133 kg\nPotencia Máxima: 13 Hp a 8000 rpm\nTorque máximo: 12.8 Nm a 6000 rpm\nTipo de motor: 4 Tiempos SOHC, refrigerado por aire\n', '149', '100', 'Urbano');


-- Bajaj
INSERT INTO `tienda_motos`.`moto` (`marca`, `linea`, `modelo`, `imagen`, `color`, `precio`, `descripcion`, `cilindraje`, `cantidad`, `categoria`) VALUES ( 'Bajaj', 'Boxer CT 100 Cargo', '2021', 'https://github.com/swsbmm/proyectoModelos1/blob/master/fotografias/Bajaj/Boxer/boxerct100cargo.png', 'Negro - Verde', '7200000', 'Peso (con aceite y tanque de gasolina lleno): 133 kg\nPotencia Máxima: 13 Hp a 8000 rpm\nTorque máximo: 12.8 Nm a 6000 rpm\nTipo de motor: 4 Tiempos SOHC, refrigerado por aire\n', '149', '100', 'Urbano');
UPDATE `tienda_motos`.`moto` SET `precio` = '3650000', `descripcion` = 'Tipo\n    4 tiempos, Monocilíndrico\n    Potencia máxima\n    8.09 HP @ 7500 rpm\n    Torque máximo\n    8.05 Nm @ 5500 rpm\n\n    Cilindrada\n    99.27 cc\n    Sistema de alimentación\n    Carburador\n    Arranque\n    Pedal\n\nVEHÍCULO\n\n    Distancia entre ejes\n    1235 mm\n    Largo x Ancho x Alto\n    1965 mm x 770 mm x 1070 mm\n    Altura al sillín\n    780 mm\n    Suspensión delantera\n    Telescópica hidráulica\n\n    Peso en vacío\n    109 Kg.\n    Tanque de combustible\n    10.5 l (2.77 gal)\n    Consumo de combustible\n    Hasta 344 km por galón*\n    Suspensión trasera\n    Doble amortiguador SNS (resorte dentro de resorte)\n\nFRENOS Y NEUMÁTICOS\n\n    Freno delantero\n    Tambor (110 mm)\n    Llanta delantera\n    2.75-17\n\n    Freno trasero\n    Tambor (110 mm)\n    Llanta trasera\n    3.00-17\n\nSISTEMA ELÉCTRICO\n\n    Sistema\n    Carburador\n\n    Batería\n    12V 2.5 Ah\n\n\n', `cilindraje` = '99' WHERE (`idmoto` = '9');

INSERT INTO `tienda_motos`.`moto` (`marca`, `linea`, `modelo`, `imagen`, `color`, `precio`, `descripcion`, `cilindraje`, `cantidad`, `categoria`) VALUES ( 'Bajaj', 'Boxer CT 100 Cargo', '2021', 'https://github.com/swsbmm/proyectoModelos1/blob/master/fotografias/Bajaj/Boxer/boxerct100cargo.png', 'Negro - Verde', '7200000', 'Peso (con aceite y tanque de gasolina lleno): 133 kg\nPotencia Máxima: 13 Hp a 8000 rpm\nTorque máximo: 12.8 Nm a 6000 rpm\nTipo de motor: 4 Tiempos SOHC, refrigerado por aire\n', '149', '100', 'Urbano');
INSERT INTO `tienda_motos`.`moto` (`marca`, `linea`, `modelo`, `imagen`, `color`, `precio`, `descripcion`, `cilindraje`, `cantidad`, `categoria`) VALUES ( 'Bajaj', 'Boxer CT 100 Cargo', '2021', 'https://github.com/swsbmm/proyectoModelos1/blob/master/fotografias/Bajaj/Boxer/boxerct100cargo.png', 'Negro - Verde', '7200000', 'Peso (con aceite y tanque de gasolina lleno): 133 kg\nPotencia Máxima: 13 Hp a 8000 rpm\nTorque máximo: 12.8 Nm a 6000 rpm\nTipo de motor: 4 Tiempos SOHC, refrigerado por aire\n', '149', '100', 'Urbano');

-- Bajaj Pulsar
INSERT INTO `tienda_motos`.`moto` (`marca`, `linea`, `modelo`, `imagen`, `color`, `precio`, `descripcion`, `cilindraje`, `cantidad`, `categoria`) VALUES ('Bajaj', 'Pulsar NS 160', '2021', 'https://github.com/swsbmm/proyectoModelos1/blob/master/fotografias/Bajaj/Pulsar/ns160-rojo.jpg', 'Rojo', '5999000', 'Tipo\n    4 tiempos, monocilíndrico de 4 válvulas, DTS-i refrigerado por aire forzado y aceite\n    Potencia máxima\n    15.3 Hp @ 8500 rpm\n    Torque máximo\n    14.6 Nm @ 6500 rpm\n\n    Cilindrada\n    160.3 cc\n    Sistema de alimentación\n    Carburador\n    Arranque\n    Eléctrico y pedal\n\nVEHÍCULO\n\n    Distancia entre ejes\n    1363 mm\n    Largo x Ancho x Alto\n    2012 x 803.5 x 1060 mm\n    Suspensión delantera\n    Telescópica hidráulica\n    Altura al sillín\n    800 mm\n\n    Peso en vacío\n    142 kg\n    Tanque de combustible\n    12 l (3.17 gal)\n    Suspensión trasera\n    Monoamortiguador Nitrox\n\nFRENOS Y NEUMÁTICOS\n\n    Freno delantero\n    Disco (240 mm)', '160 ', '150', 'Urbano');
INSERT INTO `tienda_motos`.`moto` (`marca`, `linea`, `modelo`, `imagen`, `color`, `precio`, `descripcion`, `cilindraje`, `cantidad`, `categoria`) VALUES ('Bajaj', 'Pulsar NS 160', '2021', 'https://github.com/swsbmm/proyectoModelos1/blob/master/fotografias/Bajaj/Pulsar/ns160-negro.jpg', 'Negro', '5999000', 'Tipo\n    4 tiempos, monocilíndrico de 4 válvulas, DTS-i refrigerado por aire forzado y aceite\n    Potencia máxima\n    15.3 Hp @ 8500 rpm\n    Torque máximo\n    14.6 Nm @ 6500 rpm\n\n    Cilindrada\n    160.3 cc\n    Sistema de alimentación\n    Carburador\n    Arranque\n    Eléctrico y pedal\n\nVEHÍCULO\n\n    Distancia entre ejes\n    1363 mm\n    Largo x Ancho x Alto\n    2012 x 803.5 x 1060 mm\n    Suspensión delantera\n    Telescópica hidráulica\n    Altura al sillín\n    800 mm\n\n    Peso en vacío\n    142 kg\n    Tanque de combustible\n    12 l (3.17 gal)\n    Suspensión trasera\n    Monoamortiguador Nitrox\n\nFRENOS Y NEUMÁTICOS\n\n    Freno delantero\n    Disco (240 mm)', '160 ', '150', 'Urbano');
INSERT INTO `tienda_motos`.`moto` (`marca`, `linea`, `modelo`, `imagen`, `color`, `precio`, `descripcion`, `cilindraje`, `cantidad`, `categoria`) VALUES ('Bajaj', 'Pulsar NS 160', '2021', 'https://github.com/swsbmm/proyectoModelos1/blob/master/fotografias/Bajaj/Pulsar/ns160-gris.jpg', 'Gris', '5999000', 'Tipo\n    4 tiempos, monocilíndrico de 4 válvulas, DTS-i refrigerado por aire forzado y aceite\n    Potencia máxima\n    15.3 Hp @ 8500 rpm\n    Torque máximo\n    14.6 Nm @ 6500 rpm\n\n    Cilindrada\n    160.3 cc\n    Sistema de alimentación\n    Carburador\n    Arranque\n    Eléctrico y pedal\n\nVEHÍCULO\n\n    Distancia entre ejes\n    1363 mm\n    Largo x Ancho x Alto\n    2012 x 803.5 x 1060 mm\n    Suspensión delantera\n    Telescópica hidráulica\n    Altura al sillín\n    800 mm\n\n    Peso en vacío\n    142 kg\n    Tanque de combustible\n    12 l (3.17 gal)\n    Suspensión trasera\n    Monoamortiguador Nitrox\n\nFRENOS Y NEUMÁTICOS\n\n    Freno delantero\n    Disco (240 mm)', '160 ', '150', 'Urbano');
INSERT INTO `tienda_motos`.`moto` (`marca`, `linea`, `modelo`, `imagen`, `color`, `precio`, `descripcion`, `cilindraje`, `cantidad`, `categoria`) VALUES ('Bajaj', 'Pulsar NS 160', '2021', 'https://github.com/swsbmm/proyectoModelos1/blob/master/fotografias/Bajaj/Pulsar/ns160-blanco.jpg', 'Blanco', '5999000', 'Tipo\n    4 tiempos, monocilíndrico de 4 válvulas, DTS-i refrigerado por aire forzado y aceite\n    Potencia máxima\n    15.3 Hp @ 8500 rpm\n    Torque máximo\n    14.6 Nm @ 6500 rpm\n\n    Cilindrada\n    160.3 cc\n    Sistema de alimentación\n    Carburador\n    Arranque\n    Eléctrico y pedal\n\nVEHÍCULO\n\n    Distancia entre ejes\n    1363 mm\n    Largo x Ancho x Alto\n    2012 x 803.5 x 1060 mm\n    Suspensión delantera\n    Telescópica hidráulica\n    Altura al sillín\n    800 mm\n\n    Peso en vacío\n    142 kg\n    Tanque de combustible\n    12 l (3.17 gal)\n    Suspensión trasera\n    Monoamortiguador Nitrox\n\nFRENOS Y NEUMÁTICOS\n\n    Freno delantero\n    Disco (240 mm)', '160 ', '150', 'Urbano');
