-- Yamaha ycz
INSERT INTO `tienda_motos`.`moto` ( `marca`, `linea`, `modelo`, `imagen`, `color`, `precio`, `descripcion`, `cilindraje`, `cantidad`, `categoria`) VALUES ( 'Yamaha', 'YBC', '2021', 'https://github.com/swsbmm/proyectoModelos1/blob/master/fotografias/Yamaha/YCZ/negro-rojo.jpg', 'Negro', '4350000', 'Peso (con aceite y tanque de gasolina lleno):96 kg\nPotencia máxima: 7.3 Hp a 7000 rpm\nTorque máximo: 8,6 Nm a 4500 rpm\nTipo de motor:4 Tiempos SOHC, refrigerado por aire\n', '110', '100', 'Urbano');
INSERT INTO `tienda_motos`.`moto` ( `marca`, `linea`, `modelo`, `imagen`, `color`, `precio`, `descripcion`, `cilindraje`, `cantidad`, `categoria`) VALUES ( 'Yamaha', 'YBC', '2021', 'https://github.com/swsbmm/proyectoModelos1/blob/master/fotografias/Yamaha/YCZ/yamaha-ycz-110-azul-1.jpg', 'Azul', '4350000', 'Peso (con aceite y tanque de gasolina lleno):96 kg\nPotencia máxima: 7.3 Hp a 7000 rpm\nTorque máximo: 8,6 Nm a 4500 rpm\nTipo de motor:4 Tiempos SOHC, refrigerado por aire\n', '110', '100', 'Urbano');
INSERT INTO `tienda_motos`.`moto` ( `marca`, `linea`, `modelo`, `imagen`, `color`, `precio`, `descripcion`, `cilindraje`, `cantidad`, `categoria`) VALUES ( 'Yamaha', 'YBC', '2021', 'https://github.com/swsbmm/proyectoModelos1/blob/master/fotografias/Yamaha/YCZ/yamaha-ycz-110-roja-1.jpg', 'Rojo', '4350000', 'Peso (con aceite y tanque de gasolina lleno):96 kg\nPotencia máxima: 7.3 Hp a 7000 rpm\nTorque máximo: 8,6 Nm a 4500 rpm\nTipo de motor:4 Tiempos SOHC, refrigerado por aire\n', '110', '100', 'Urbano');


-- Yamaha fz
INSERT INTO `tienda_motos`.`moto` (`marca`, `linea`, `modelo`, `imagen`, `color`, `precio`, `descripcion`, `cilindraje`, `cantidad`, `categoria`) VALUES ( 'Yamaha', 'FZ', '2021', 'https://github.com/swsbmm/proyectoModelos1/blob/master/fotografias/Yamaha/FZ/fz-azul.jpg', 'Azul', '7200000', 'Peso (con aceite y tanque de gasolina lleno): 133 kg\nPotencia Máxima: 13 Hp a 8000 rpm\nTorque máximo: 12.8 Nm a 6000 rpm\nTipo de motor: 4 Tiempos SOHC, refrigerado por aire\n', '149', '100', 'Urbano');
INSERT INTO `tienda_motos`.`moto` ( `marca`, `linea`, `modelo`, `imagen`, `color`, `precio`, `descripcion`, `cilindraje`, `cantidad`, `categoria`) VALUES ( 'Yamaha', 'FZ', '2021', 'https://github.com/swsbmm/proyectoModelos1/blob/master/fotografias/Yamaha/FZ/fz-black_mate.jpg', 'Negro Mate', '7200000', 'Peso (con aceite y tanque de gasolina lleno): 133 kg\nPotencia Máxima: 13 Hp a 8000 rpm\nTorque máximo: 12.8 Nm a 6000 rpm\nTipo de motor: 4 Tiempos SOHC, refrigerado por aire\n', '149', '100', 'Urbano');
INSERT INTO `tienda_motos`.`moto` (`marca`, `linea`, `modelo`, `imagen`, `color`, `precio`, `descripcion`, `cilindraje`, `cantidad`, `categoria`) VALUES ( 'Yamaha', 'FZ', '2021', 'https://github.com/swsbmm/proyectoModelos1/blob/master/fotografias/Yamaha/FZ/fz-blanca.jpg', 'Blanco', '7200000', 'Peso (con aceite y tanque de gasolina lleno): 133 kg\nPotencia Máxima: 13 Hp a 8000 rpm\nTorque máximo: 12.8 Nm a 6000 rpm\nTipo de motor: 4 Tiempos SOHC, refrigerado por aire\n', '149', '100', 'Urbano');
INSERT INTO `tienda_motos`.`moto` (`marca`, `linea`, `modelo`, `imagen`, `color`, `precio`, `descripcion`, `cilindraje`, `cantidad`, `categoria`) VALUES ( 'Yamaha', 'FZ', '2021', 'https://github.com/swsbmm/proyectoModelos1/blob/master/fotografias/Yamaha/FZ/fz-gris.jpg', 'Gris', '7200000', 'Peso (con aceite y tanque de gasolina lleno): 133 kg\nPotencia Máxima: 13 Hp a 8000 rpm\nTorque máximo: 12.8 Nm a 6000 rpm\nTipo de motor: 4 Tiempos SOHC, refrigerado por aire\n', '149', '100', 'Urbano');
INSERT INTO `tienda_motos`.`moto` (`marca`, `linea`, `modelo`, `imagen`, `color`, `precio`, `descripcion`, `cilindraje`, `cantidad`, `categoria`) VALUES ( 'Yamaha', 'FZ', '2021', 'https://github.com/swsbmm/proyectoModelos1/blob/master/fotografias/Yamaha/FZ/fz-roja.jpg', 'Roja', '7200000', 'Peso (con aceite y tanque de gasolina lleno): 133 kg\nPotencia Máxima: 13 Hp a 8000 rpm\nTorque máximo: 12.8 Nm a 6000 rpm\nTipo de motor: 4 Tiempos SOHC, refrigerado por aire\n', '149', '100', 'Urbano');
